package com.zhongjh.libpedometerstoday.store.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhongjh.libpedometerstoday.store.db.PedometersToday;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pedometersTodayDaoConfig;

    private final PedometersTodayDao pedometersTodayDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pedometersTodayDaoConfig = daoConfigMap.get(PedometersTodayDao.class).clone();
        pedometersTodayDaoConfig.initIdentityScope(type);

        pedometersTodayDao = new PedometersTodayDao(pedometersTodayDaoConfig, this);

        registerDao(PedometersToday.class, pedometersTodayDao);
    }
    
    public void clear() {
        pedometersTodayDaoConfig.clearIdentityScope();
    }

    public PedometersTodayDao getPedometersTodayDao() {
        return pedometersTodayDao;
    }

}
